modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/JesseRWeigel/demigods-fate/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="Jesse Weigel & Ambrose"
description='''
A Percy Jackson RPG mod for Minecraft. Choose your godly parent, train at Camp Half-Blood or Camp Jupiter, and embark on prophecy-driven quests through the world of Greek and Roman mythology.

Features demigod abilities, celestial bronze weapons, mythological monsters, and storylines from the Percy Jackson, Heroes of Olympus, and Trials of Apollo series.
'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
